<template>
  <div class="text-area">
    <h1>Hello</h1>
    <h3>Use this AI text generator to effortlessly create content for your next blog. 
      Once generated, your content will be structured and sent directly to your 
      Umbraco backoffice for seamless integration.
    </h3>
  </div>
  <div class="openai-input">
    <div class="textarea-container">
      <textarea 
        v-model="userPrompt" 
        placeholder="Enter your prompt here to help me generate your next blog post..." 
        rows="4" 
        cols="50"
        class="custom-textarea">
      </textarea>
      <button 
        @click="fetchOpenAI" 
        :disabled="isNodeLoading" 
        class="send-button">
        <i class="fas fa-paper-plane"></i>
      </button>
    </div>

    <div class="text-reminder">
      <p>Content generated by AI is based on the data it has been trained on and may lack originality, depth, or personal perspective. 
        While AI can assist in the creation process, it is essential to verify, refine, and credit sources to ensure quality and compliance with copyright standards. 
      </p>
    </div>
    
    <div v-if="aiResponse">
      <h3>{{ aiResponse.title }}</h3>
      <p>{{ aiResponse.body }}</p>
    </div>
    
    <div v-if="successMessage" class="success-message">
      <p>{{ successMessage }}</p>
    </div>
    
    <div v-if="error" class="error-message">
      <p>Fejl: {{ error }}</p>
    </div>
  </div>

  <!-- White box with green button -->
  <div class="bottom-box">
    <button class="send-to-umbraco-button">Send to Umbraco  </button>
  </div>
</template>

<script setup>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { ref } from 'vue';
import { getToken } from '../services/apiService';
import { fetchOpenAIResponse, createContentNode } from '../services/apiService';

const userPrompt = ref('');
const aiResponse = ref(null);
const isNodeLoading = ref(false);
const successMessage = ref(null);
const error = ref(null);

const fetchOpenAI = async () => {
  isNodeLoading.value = true;
  error.value = null;
  aiResponse.value = null;

  try {
    const prompt = userPrompt.value.trim();
    if (!prompt) {
      throw new Error("Prompt kan ikke være tom.");
    }

    // Check if response is already saved in localStorage
    let savedResponse = localStorage.getItem('openaiResponse');
    if (savedResponse) {
      aiResponse.value = JSON.parse(savedResponse); 
      console.log("Bruger gemt OpenAI response:", aiResponse.value);  
      return;
    }

    // Proceed with OpenAI request if no saved response
    const token = await getToken();
    const response = await fetchOpenAIResponse(prompt, token);

    if (!response || typeof response !== 'object' || !response.response) {
      throw new Error("Ugyldigt svar fra serveren.");
    }

    aiResponse.value = response.response;
    localStorage.setItem('openaiResponse', JSON.stringify(response.response));  
    console.log("Gemte OpenAI-respons i localStorage:", response.response); 

    const umbracoResponse = await createContentNode(aiResponse.value, token);
    successMessage.value = "Content node er oprettet i Umbraco!";
  } catch (err) {
    error.value = err.message || "En ukendt fejl opstod.";
    console.error("Fejl ved OpenAI-anmodning:", err);
  } finally {
    isNodeLoading.value = false;
  }
};

defineExpose({
  fetchOpenAI,
  aiResponse,
  isNodeLoading,
  successMessage,
  error,
  userPrompt
});
</script>

<style scoped>
.text-area {
  margin: 164px auto 40px; 
  width: 587px;
  display: flex;
  flex-direction: column;
  align-items: center;  
  justify-content: center; 
  text-align: center; 
}

h1 {
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 20px;
}

h3 {
  font-size: 18px;
  font-weight: 200;
  line-height: 30px;
}

.textarea-container {
  position: relative; 
  display: inline-block; 
  width: 842px; 
}

.custom-textarea {
  width: 100%; 
  height: 132px;
  background-color: #fff;
  border: 1px solid #C2C2C2;
  color: #000; 
  border-radius: 5px;
  padding: 10px 50px 10px 10px;
  font-size: 15px;
  font-family: Arial, sans-serif;
  outline: none;
  box-sizing: border-box;
}

.send-button {
  position: absolute;
  top: 80%; 
  right: 20px; 
  transform: translateY(-50%) rotate(30deg);
  background-color: transparent; 
  border: none;
  width: auto; 
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  color: #3545B0; 
  font-size: 20px;
  padding: 0;
}

.text-reminder {
  margin: 136px auto;
  margin-bottom: 20px;
  width: 795px;
  text-align: center;
}

p {
  font-size: 12px;
  color: #1B254F;
}

.bottom-box {
  position: fixed;
  bottom: 0;
  width: 100%; 
  height: 76px;
  background-color: white; 
  padding: 6px 21px; 
  display: flex; 
  justify-content: flex-end;
  align-items: center; 
}

.send-to-umbraco-button {
  background-color: #4CAF50; 
  color: white; 
  border: none; 
  padding: 12px 42px; 
  border-radius: 5px;
  font-size: 20px; 
  margin: 20px 30px;
  cursor: pointer;
  font-size: 16px;
}

</style>
