<template>
    <div class="text-reminder">
      <p>
        Content generated by AI is based on the data it has been trained on and may lack originality, depth, or personal perspective. 
        While AI can assist in the creation process, it is essential to verify, refine, and credit sources to ensure quality and compliance with copyright standards.
      </p>
    </div>
  </template>
  
  <script setup>
  </script>
  
  <style scoped>
  .text-reminder {
    position: fixed;  
    bottom: 110px;   
    left: 50%;      
    transform: translateX(-50%); 
    width: 795px;    
    text-align: center; 
  }
  
  p {
    font-size: 12px;
    color: #1B254F;
    margin: 0;  
  }
  </style>
  